[tools.shodan_host]
name = "shodan_host"
description = "Shodan intelligence for the IP address"
command = "shodan"
args = [
    "host",
    "{target}"
]
output_file = "shodan_{target}.txt"
category = "intelligence"
dependencies = ["shodan"]
