[tools.shodan_basic]
name = "shodan_basic"
description = "Shodan host information"
command = "shodan"
args = [
    "host",
    "{target}"
]
output_file = "shodan_{target}.txt"
category = "intelligence"
dependencies = ["shodan"]
parse_strategy = "llm"
output_format = "json"
requires_sudo = false
timeout_seconds = 60