[tools.nmap_default]
name = "nmap_default"
description = "Scan top 1000 ports with service detection"
command = "nmap"
args = [
    "-sV",
    "-O",
    "--top-ports 1000",
    "-oN",
    "-",
    "-oX",
    "-",
    "{target}"
]
output_file = "nmap_default_{target}.txt"
category = "scanning"
dependencies = ["nmap"]
parse_strategy = "llm"
output_format = "json"
requires_sudo = false
timeout_seconds = 300

[tools.nmap_stealth]
name = "nmap_stealth"
description = "Stealth SYN scan of top ports"
command = "nmap"
args = [
    "-sS",
    "-sV",
    "--top-ports 1000",
    "-oN",
    "-",
    "-oX",
    "-",
    "{target}"
]
output_file = "nmap_stealth_{target}.txt"
category = "scanning"
dependencies = ["nmap"]
parse_strategy = "llm"
output_format = "json"
requires_sudo = true
timeout_seconds = 600

[tools.nmap_range]
name = "nmap_range"
description = "Scan custom port range with service detection"
command = "nmap"
args = [
    "-sV",
    "-O",
    "-p",
    "{port_range}",
    "-oN",
    "-",
    "-oX",
    "-",
    "{target}"
]
output_file = "nmap_range_{target}_{port_range}.txt"
category = "scanning"
dependencies = ["nmap"]
parse_strategy = "llm"
output_format = "json"
requires_sudo = false
timeout_seconds = 600

[tools.rustscan_default]
name = "rustscan_default"
description = "Fast port scanning with RustScan"
command = "rustscan"
args = [
    "-a",
    "{target}",
    "--",
    "-sV"
]
output_file = "rustscan_{target}.txt"
category = "scanning"
dependencies = ["rustscan", "nmap"]
parse_strategy = "llm"
output_format = "json"
requires_sudo = false
timeout_seconds = 180