# Clippy configuration for ipcrawler

# Warn on common issues
warn = [
    "clippy::all",
    "clippy::pedantic",
    "clippy::nursery",
    "clippy::cargo",
]

# Deny dangerous patterns
deny = [
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::panic",
    "clippy::unimplemented",
    "clippy::todo",
]

# Allow some patterns that are okay in this project
allow = [
    "clippy::module_name_repetitions",
    "clippy::must_use_candidate",
    "clippy::missing_errors_doc",
]

# Configure specific lints
cognitive-complexity-threshold = 30
too-many-lines-threshold = 200
type-complexity-threshold = 400
single-char-binding-names-threshold = 4