# Pre-commit hooks for Rust validation
repos:
  - repo: local
    hooks:
      # Rust formatting
      - id: cargo-fmt
        name: Cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
        
      # Rust linting
      - id: cargo-clippy
        name: Cargo clippy
        entry: cargo clippy --all-targets --all-features -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
        
      # Rust tests
      - id: cargo-test
        name: Cargo test
        entry: cargo test --all-features
        language: system
        types: [rust]
        pass_filenames: false
        
      # YAML validation
      - id: yaml-check
        name: YAML Check
        entry: python3 -c "import yaml; yaml.safe_load(open('${FILE}'))"
        language: system
        files: \\.ya?ml$
        
      # Schema validation for tools.yaml
      - id: tools-yaml-validation
        name: Tools YAML Schema Validation
        entry: cargo run --bin validate-tools-config
        language: system
        files: ^config/tools\.yaml$
        pass_filenames: false
        
      # Security audit
      - id: cargo-audit
        name: Cargo audit
        entry: cargo audit
        language: system
        pass_filenames: false
        
      # Unused dependencies check
      - id: cargo-machete
        name: Cargo machete
        entry: cargo machete
        language: system
        pass_filenames: false

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
        
  # Additional YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yml]
        
  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: [--config=.markdownlint.json]