# YAML linting configuration
extends: default

rules:
  # Allow longer lines for readability
  line-length:
    max: 120
    
  # Allow indentation for better structure
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
    
  # Be more flexible with comments
  comments:
    min-spaces-from-content: 1
    
  # Allow document start markers to be optional
  document-start: disable
  
  # Allow truthy values like "yes", "on"
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']