[package]
name = "ipcrawler"
version = "0.1.0"
edition = "2021"
authors = ["Neur0map <contact@neur0map.io>"]
description = "IP-focused reconnaissance tool for penetration testing"
license = "MIT"

[[bin]]
name = "ipcrawler"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
clap = { version = "4.0", features = ["derive"] }
tera = "1.19"
indicatif = "0.17"
colored = "2.0"
anyhow = "1.0"
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
futures = "0.3"
async-trait = "0.1"
