[package]
name = "ipcrawler"
version = "0.1.0"
edition = "2021"
authors = ["neur0map"]
description = "Intelligent automated penetration testing scanner with ML-based output parsing"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
tokio = { version = "1.42", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.12", features = ["json"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
colored = "2.1"
libc = "0.2"
toml = "0.8"
inquire = "0.7"
dirs = "5.0"
rpassword = "7.3"
terminal_size = "0.3"

[dev-dependencies]
tempfile = "3.10"
