[package]
name = "ipcrawler"
version = "0.1.0-alpha"
edition = "2021"
authors = ["ipcrawler"]

[dependencies]
# CLI + serde
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"

# Async + process handling
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
futures = "0.3"

# Output & UX
crossterm = "0.27"
unicode-width = "0.1"

# System monitoring
sysinfo = "0.30"

# Logging & errors
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
thiserror = "1"
anyhow = "1"

# Helpers
regex = "1"
quick-xml = "0.36"
async-trait = "0.1"
which = "6"
libc = "0.2"
minijinja = { version = "2", features = ["loader"] }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tempfile = "3.0"

# Optimize for release builds
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

# Make dev builds faster to compile
[profile.dev]
opt-level = 0

