[package]
name = "ipcrawler"
version = "0.1.0"
edition = "2021"
authors = ["neur0map"]
description = "Auto-reconnaissance tool with RAG for intelligent querying"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.42", features = ["full"] }
tokio-stream = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
notify = { version = "6.1", default-features = false, features = ["macos_fsevent"] }
notify-debouncer-full = "0.3"
swiftide = { version = "0.13", features = ["qdrant", "openai"] }
qdrant-client = "1.11"
keyring = "2.3"
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
glob = "0.3"
regex = "1.10"
async-trait = "0.1"
futures = "0.3"
dialoguer = "0.11"
indicatif = "0.17"
colored = "2.1"
reqwest = { version = "0.12", features = ["json"] }
dirs = "5.0"

[dev-dependencies]
tempfile = "3.10"
