[package]
name = "ipcrawler"
version = "0.1.1"
edition = "2021"
authors = ["neur0map"]
description = "Intelligent automated penetration testing scanner with AI-powered output parsing"
license = "MIT"
repository = "https://github.com/neur0map/ipcrawler"
homepage = "https://github.com/neur0map/ipcrawler"
documentation = "https://github.com/neur0map/ipcrawler/blob/main/README.md"
readme = "README.md"
keywords = ["security", "pentesting", "scanner", "ai", "llm"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
tokio = { version = "1.42", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
colored = "2.1"
libc = "0.2"
toml = "0.8"
regex = "1.10"
inquire = "0.7"
dirs = "5.0"
rpassword = "7.3"
terminal_size = "0.3"
ipnetwork = "0.20"
indicatif = "0.17"
atty = "0.2"

[dev-dependencies]
tempfile = "3.10"
