[package]
name = "ipcrawler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
chrono = { version = "0.4", features = ["serde"] }
colored = "2.0"
indicatif = "0.17"
shell-words = "1.1"
futures = "0.3"
directories = "5.0"
serde_json = "1.0"
regex = "1.0"

# Table formatting
comfy-table = "7.1"

# Tool detection
which = "6.0"

# Enhanced JSON and template processing
minijinja = { version = "2.4", features = ["loader"] }
serde_json_path = "0.7"
pulldown-cmark = "0.13"
comrak = { version = "0.28", features = ["syntect"] }

# Error handling and notifications
human-panic = "2.0"
notify-rust = { version = "4.0", optional = true }

# Validation and Schema (dev-only features)
schemars = { version = "0.8", optional = true }
jsonschema = { version = "0.18", optional = true }
validator = { version = "0.18", features = ["derive"], optional = true }

# Runtime validation
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
# Testing tools
proptest = "1.5"
quickcheck = "1.0"
quickcheck_macros = "1.0"
rstest = "0.21"
insta = { version = "1.40", features = ["yaml"] }
pretty_assertions = "1.4"

# Benchmarking
criterion = { version = "0.5", features = ["html_reports"] }
dhat = "0.3"

# Code coverage tool (installed separately with cargo install cargo-tarpaulin)

# Fuzzing
arbitrary = { version = "1.3", features = ["derive"] }
# cargo-fuzz is installed separately with cargo install cargo-fuzz

# Features for conditional compilation
[features]
default = []
dev-tools = ["schemars", "jsonschema", "validator"]  # Optional schema validation dependencies
full-validation = ["dev-tools"]

# Production optimizations
[profile.release]
debug = false
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
opt-level = 3

# Lean profile for minimal binary size
[profile.lean]
inherits = "release"
opt-level = "z"
debug = false
strip = "symbols"
lto = true
codegen-units = 1
panic = "abort"

[[bench]]
name = "parser_bench"
harness = false
required-features = ["dev-tools"]

[[bench]]
name = "discovery_bench" 
harness = false
required-features = ["dev-tools"]
