# IP Crawler Configuration

# Application Version
version: "1.0.0-alpha.1"

# Scan Settings
scan:
  # DEFAULT BEHAVIOR: ONLY SCAN DISCOVERED OPEN PORTS
  # 
  # When true (DEFAULT): 
  #   1. Fast nmap discovers which ports are open (~30 seconds)
  #   2. Detailed nmap ONLY scans those specific open ports
  #
  # When false:
  #   1. Skip port discovery
  #   2. Nmap scans ALL 65535 ports (10+ minutes)
  #
  fast_port_discovery: true  # DEFAULT: true (recommended)
  
  # Maximum ports to scan in detail
  # If more ports are discovered, only top N will be scanned
  max_detailed_ports: 1000

# Privilege Settings
privileges:
  # Prompt for sudo escalation when running without root privileges
  # When true (DEFAULT): Ask user if they want to restart with sudo
  # When false: Never prompt, continue with current privileges
  prompt_for_sudo: true
  
  # Auto-escalate to sudo without prompting (for automation)
  # When true: Automatically restart with sudo if available
  # When false: Follow prompt_for_sudo setting
  auto_escalate: false

# Parallel Processing
parallel:
  # Number of concurrent scan processes
  batch_size: 10
  
  # Ports per batch when scanning all ports
  ports_per_batch: 6553

# Output Settings
output:
  # Save raw XML output from tools
  save_raw_xml: false
  
  # Verbose console output
  verbose: false
  
  # Raw script output
  # When false (default): Cleans binary/hex data from script outputs
  # When true: Keeps all output as-is (including binary garbage)
  raw_output: false
  
  # Save results in real-time to workspace during scanning
  # When true (default): Creates live_results.json that updates as scan progresses
  # When false: Only save final results after scan completion
  real_time_save: true

# SmartList Enhanced Discovery
smartlist:
  # Enable intelligent path discovery using SmartList algorithm
  enabled: true
  
  # Maximum number of wordlists to use per service
  max_wordlists: 3
  
  # Minimum confidence level for wordlist recommendations
  # Options: HIGH, MEDIUM, LOW
  min_confidence: "MEDIUM"
  
  # Maximum paths to test per wordlist
  max_paths_per_wordlist: 100
  
  # Timeout for path checking requests (seconds)
  request_timeout: 5
  
  # Maximum concurrent path checks
  max_concurrent_requests: 20
  
  # Temporary directory for wordlist files (relative to database/)
  temp_directory: "temp"

# Path Discovery Settings
discovery:
  # Enable enhanced path discovery methods
  enabled: true
  
  # Maximum total paths to discover per service
  max_total_paths: 500
  
  # Include common application patterns
  include_common_paths: true
  
  # Include technology-specific paths
  include_tech_paths: true
  
  # Custom additional paths to check (added to common paths)
  custom_paths: []

# Tool Paths (leave empty to use system PATH)
tools:
  nmap_path: ""

