# IPCrawler SmartList Engine Configuration

# Application Version
version: "0.1.2-alpha.4"

# SmartList Analysis Settings
scan:
  # DEFAULT BEHAVIOR: FAST SERVICE DISCOVERY FOR WORDLIST RECOMMENDATIONS
  # 
  # When true (DEFAULT): 
  #   1. Fast service detection to profile target (~30 seconds)
  #   2. SmartList Engine recommends optimal wordlists based on discovered services
  #
  # When false:
  #   1. Skip fast discovery phase
  #   2. Comprehensive analysis of all services (10+ minutes)
  #
  fast_port_discovery: true  # DEFAULT: true (recommended)
  
  # Maximum services to analyze for recommendations
  # If more services are discovered, only top N will be analyzed
  max_detailed_ports: 1000

# Privilege Settings
privileges:
  # Prompt for sudo escalation for enhanced service fingerprinting
  # When true (DEFAULT): Ask user if they want better analysis with sudo
  # When false: Never prompt, use basic fingerprinting only
  prompt_for_sudo: true
  
  # Auto-escalate to sudo without prompting (for automation)
  # When true: Automatically use enhanced fingerprinting if available
  # When false: Follow prompt_for_sudo setting
  auto_escalate: false

# Output Settings
output:
  # Save raw analysis data from tools
  save_raw_xml: false
  
  # Verbose SmartList recommendations
  verbose: false
  
  # Raw analysis output
  # When false (default): Cleans and formats recommendations
  # When true: Keeps all raw analysis data
  raw_output: false

# Tool Paths (leave empty to use system PATH)
tools:
  nmap_path: ""

