[application]
name = "ipcrawler"
version = "0.1.0-alpha"
debug = false

[performance]
concurrent_limit = 10
default_timeout = 80
max_output_size = 1048576
memory_limit = 512

[security]
enforce_validation = true
allow_shell_commands = false
max_template_size = 1048576

[system]
config_dir = "configs"
templates_dir = "templates"
results_dir = "results"
cache_dir = ".cache"

[logging]
silent = true
level = "INFO"
file_rotation = true
max_log_size = 10485760

[retry]
count = 3
backoff_multiplier = 2
max_wait_time = 60

[ui]
enable_rich_ui = true
fullscreen_mode = false
refresh_rate = 2
theme = "minimal"

[wordlists]
seclists_path = "/Users/carlosm/.local/share/seclists"
