# ipcrawler Configuration File
# Define custom template flags for easy scanning

[templates]
# Format: flag_name = "folder_name"
# Usage: ipcrawler -flag_name target

# Run all tools in the default folder
default = "default"

# Run all tools in the recon folder  
recon = "recon"

# Run all tools in the custom folder (advanced multi-step scans)
custom = "custom"

# Run all tools in the htb folder (HTB specific templates)
htb = "htb"

# Add your custom template folders here
# Example:
# user = "custom_folder"
# web = "web_scanning"
# network = "network_tools"

[settings]
# Global settings for ipcrawler
templates_dir = "templates"
concurrent_limit = 10
default_timeout = 60

[logging]
# Logging configuration
silent = true

[retry]
# Retry logic configuration
count = 3
backoff_multiplier = 2
max_wait_time = 60

# =============================================================================
# PRESET SYSTEM - Global argument presets for common tool configurations
# =============================================================================
# Presets allow templates to use predefined argument sets instead of 
# specifying complex command-line flags manually.
#
# Usage in templates:
#   "preset": "tool.preset_name"
#   "args": ["{{target}}"]  # Additional args as needed
#
# Benefits:
#   - Simplified template creation (3-5 lines vs 20+ lines)
#   - No need to learn complex tool-specific flags
#   - Consistent output formatting across templates
#   - Easy maintenance and updates of common configurations

[presets]
# =============================================================================
# GLOBAL PRESETS - Common patterns used across multiple tools
# =============================================================================
timeout_fast = ["--timeout", "10"]
timeout_slow = ["--timeout", "60"]
quiet_mode = ["-q"]
verbose_mode = ["-v"]

# =============================================================================
# NMAP PRESETS - Network scanning configurations
# =============================================================================
[presets.nmap]
# Quick TCP scan - Fast reconnaissance
quick_tcp = ["-sT", "-T4", "--top-ports", "1000", "--open"]

# Stealth scan - Low noise reconnaissance  
stealth = ["-sS", "-T1", "-f", "--randomize-hosts"]

# Service detection - Identify running services
service_scan = ["-sV", "-sC", "-T4", "--version-intensity", "5"]

# Full port scan - Comprehensive but slow
full_ports = ["-p-", "-T4", "--min-rate", "1000"]

# UDP scan - Common UDP services
udp_common = ["-sU", "--top-ports", "100", "-T4"]

# Vulnerability scan - Using NSE scripts
vuln_scan = ["-sV", "--script", "vuln", "-T4"]

# =============================================================================
# CURL PRESETS - HTTP/HTTPS request configurations
# =============================================================================
[presets.curl]
# Basic information gathering
basic_info = ["-s", "-I", "--max-time", "30", "--connect-timeout", "10"]

# Full header analysis with redirect following
full_headers = ["-s", "-I", "-L", "--max-time", "30", "--connect-timeout", "10", "-w", "Status: %{http_code}\\nTime: %{time_total}s\\nSize: %{size_download}\\nRedirect: %{redirect_url}\\n"]

# Virtual host discovery with custom formatting
vhost_check = ["-s", "-I", "--connect-timeout", "5", "--max-time", "15", "-w", "\\n--- VHOST CHECK ---\\nStatus: %{http_code}\\nSize: %{size_download}\\nTime: %{time_total}s\\nFinal-URL: %{url_effective}\\n"]

# Fast content fetch
fast_content = ["-s", "--max-time", "15", "--connect-timeout", "5"]

# Verbose debugging
debug_mode = ["-v", "--max-time", "30", "-w", "\\n--- DEBUG INFO ---\\nHTTP: %{http_code}\\nTime: %{time_total}s\\nSize: %{size_download}\\n"]

# =============================================================================
# FEROXBUSTER PRESETS - Directory/file enumeration configurations (CTF optimized)
# =============================================================================
[presets.feroxbuster]
# CTF Fast scan - Focus on accessible content and redirects
ctf_fast = ["-t", "20", "-s", "200,301,302", "--dont-filter", "-q", "--no-state"]

# CTF Deep scan - Include forbidden paths that might be accessible
ctf_deep = ["-t", "50", "-s", "200,301,302,403", "--dont-filter", "-q", "--no-state", "--depth", "3", "--auto-tune"]

# CTF Stealth scan - Low noise for sensitive targets
ctf_stealth = ["-t", "5", "-s", "200,301,302", "--dont-filter", "-q", "--no-state", "--rate-limit", "10"]

# CTF Extensions scan - Common CTF file types
ctf_extensions = ["-t", "20", "-s", "200,301,302,403", "--dont-filter", "-q", "--no-state", "-x", "php,html,js,txt,xml,json,flag,key,config"]

# CTF Backup files scan - Look for exposed sensitive files
ctf_backup = ["-t", "15", "-s", "200,301,302,403", "--dont-filter", "-q", "--no-state", "-x", "bak,backup,old,tmp,~,flag,key"]

# Legacy presets (backwards compatibility)
fast_scan = ["-t", "20", "-s", "200,301,302", "--dont-filter", "-q", "--no-state"]
deep_scan = ["-t", "50", "-s", "200,301,302,403", "--dont-filter", "-q", "--no-state", "--depth", "3", "--auto-tune"]
stealth_scan = ["-t", "5", "-s", "200,301,302", "--dont-filter", "-q", "--no-state", "--rate-limit", "10"]
extensions_scan = ["-t", "20", "-s", "200,301,302,403", "--dont-filter", "-q", "--no-state", "-x", "php,html,js,txt,xml,json"]
backup_scan = ["-t", "15", "-s", "200,301,302,403", "--dont-filter", "-q", "--no-state", "-x", "bak,backup,old,tmp,~"]

# =============================================================================
# GOBUSTER PRESETS - Multi-purpose enumeration configurations (CTF optimized)
# =============================================================================
[presets.gobuster]
# CTF Virtual host discovery - Focus on accessible content
ctf_vhost_fast = ["vhost", "-t", "20", "-q", "--timeout", "5s", "--no-progress"]
ctf_vhost_thorough = ["vhost", "-t", "50", "-q", "--timeout", "10s", "--no-progress"]

# CTF Directory enumeration - Focus on important status codes
ctf_dir_fast = ["dir", "-t", "20", "-q", "--no-progress", "-s", "200,301,302,403"]
ctf_dir_extensions = ["dir", "-t", "20", "-q", "--no-progress", "-x", "php,html,js,txt,xml,json,flag,key,config", "-s", "200,301,302,403"]

# CTF DNS subdomain enumeration
ctf_dns_fast = ["dns", "-t", "20", "-q"]
ctf_dns_thorough = ["dns", "-t", "50", "-q", "--wildcard"]

# Legacy presets (backwards compatibility)
vhost_fast = ["vhost", "-t", "20", "-q", "--timeout", "5s", "--no-progress"]
vhost_thorough = ["vhost", "-t", "50", "-q", "--timeout", "10s", "--no-progress"]
dir_fast = ["dir", "-t", "20", "-q", "--no-progress", "-s", "200,301,302,403"]
dir_extensions = ["dir", "-t", "20", "-q", "--no-progress", "-x", "php,html,js,txt,xml", "-s", "200,301,302,403"]
dns_fast = ["dns", "-t", "20", "-q"]
dns_thorough = ["dns", "-t", "50", "-q", "--wildcard"]

# =============================================================================
# DIG PRESETS - DNS query configurations
# =============================================================================
[presets.dig]
# Basic DNS lookups
basic_lookup = ["+short"]
full_lookup = ["+trace", "+additional"]

# Record type specific
mx_records = ["MX", "+short"]
txt_records = ["TXT", "+short"]
ns_records = ["NS", "+short"]
a_records = ["A", "+short"]

# =============================================================================
# NUCLEI PRESETS - Vulnerability scanning configurations
# =============================================================================
[presets.nuclei]
# Quick vulnerability scan
quick_scan = ["-t", "exposures/", "-silent", "-rl", "50"]

# Comprehensive scan
full_scan = ["-t", "vulnerabilities/", "-t", "exposures/", "-t", "misconfiguration/", "-silent", "-rl", "100"]

# CVE specific scanning
cve_scan = ["-t", "cves/", "-silent", "-rl", "30"]

# Technology detection
tech_detection = ["-t", "technologies/", "-silent", "-rl", "50"]

# =============================================================================
# PING PRESETS - Basic connectivity testing
# =============================================================================
[presets.ping]
# Basic connectivity test
basic = ["-c", "1"]
# Multiple ping test  
multi = ["-c", "4"]
# Fast ping test
fast = ["-c", "1", "-W", "2"]

# =============================================================================
# ECHO PRESETS - Basic output testing (for testing/debugging)
# =============================================================================
[presets.echo]
# Basic echo
basic = []
# Echo with formatting
formatted = ["-e"]

# =============================================================================
# OPENSSL PRESETS - SSL/TLS certificate analysis
# =============================================================================
[presets.openssl]
# Basic certificate info
cert_info = ["s_client", "-connect", "{{target}}:443", "-servername", "{{target}}", "-showcerts"]
# Certificate details
cert_details = ["x509", "-in", "/dev/stdin", "-text", "-noout"]

# =============================================================================
# NSLOOKUP PRESETS - DNS lookup configurations  
# =============================================================================
[presets.nslookup]
# Basic DNS lookup
basic = []
# Detailed lookup with type specification
detailed = ["-type=ANY"]

