# ipcrawler Core Configuration
# Global system behavior and performance settings

[application]
name = "ipcrawler"
version = "0.1.0-alpha"
debug = false

[performance]
# Execution performance settings
concurrent_limit = 10
default_timeout = 80
max_output_size = 1048576  # 1MB
memory_limit = 512  # MB

[security]
# Core security settings
enforce_validation = true
allow_shell_commands = false
max_template_size = 1048576  # 1MB

[system]
# System paths and directories
config_dir = "configs"
templates_dir = "templates"
results_dir = "results"
cache_dir = ".cache"

[logging]
# Logging configuration
silent = true
level = "INFO"
file_rotation = true
max_log_size = 10485760  # 10MB

[retry]
# Retry logic configuration
count = 3
backoff_multiplier = 2
max_wait_time = 60