# ipcrawler Global Configuration
# Configuration for active DNS reconnaissance plugins

[metadata]
version = "0.1.0"
description = "Global configuration for ipcrawler DNS reconnaissance tools"

# ========================================
# CONCURRENCY & PERFORMANCE SETTINGS
# ========================================

[concurrency]
# Total concurrent operations allowed
max_total_scans = 50

# Port scanning pool size  
max_port_scans = 10

# Service scanning pool size (auto-calculated: max_total_scans - max_port_scans)
max_service_scans = 40

# File descriptor requirements
# If you get "too many open files" errors, increase your system limit:
# Linux/macOS: ulimit -n 4096  (temporary)
# Linux permanent: Add "* soft nofile 4096" and "* hard nofile 8192" to /etc/security/limits.conf
# macOS permanent: Add "limit maxfiles 4096 8192" to ~/.zshrc or ~/.bash_profile
min_file_descriptors = 1024
recommended_file_descriptors = 2048

# ========================================
# DNS RECONNAISSANCE TOOLS
# ========================================
# Uncomment any section below to override default plugin behavior

# [tools.nslookup]
# # Override default command and arguments
# command = "nslookup"
# base_args = []

# # Override DNS query options
# [tools.nslookup.options]
# record_types = ["A", "AAAA", "MX", "NS", "TXT", "PTR"]
# reverse_dns = true              # Enable PTR lookups for IPs
# recursive = true               # Use recursive DNS queries
# delay_between_queries_ms = 500 # Be nice to DNS servers

# # Override timeouts and limits
# [tools.nslookup.limits]
# timeout_ms = 10000             # 10 seconds per query
# max_retries = 2
# total_timeout_ms = 30000       # 30 seconds total per target

# [tools.dig]
# # Override default command and arguments for better output formatting
# command = "dig"
# base_args = ["+short", "+time=3", "+tries=2"]

# # Override DNS query options
# [tools.dig.options]
# record_types = ["A", "AAAA", "MX", "NS", "TXT", "CNAME", "SOA", "PTR"]
# reverse_dns = true              # Enable PTR lookups for IPs
# recursive = true               # Use recursive DNS queries
# delay_between_queries_ms = 250 # Faster than nslookup due to +short output
# include_additional_records = false

# # Override timeouts and limits
# [tools.dig.limits]
# timeout_ms = 10000             # 10 seconds per query
# max_retries = 2
# total_timeout_ms = 30000       # 30 seconds total per target
# query_timeout_ms = 3000        # 3 seconds per individual query (+time=3)

# [tools.hosts_discovery]
# # Enable/disable hosts discovery and automatic /etc/hosts updates
# enabled = true                  # Enable hosts discovery plugin
# target_ip = "127.0.0.1"        # IP to map discovered domains to
# auto_write = true              # Automatically write to /etc/hosts if sudo available
# backup_hosts = true            # Create backup before modifying /etc/hosts

# # dnsx configuration for subdomain enumeration
# [tools.hosts_discovery.dnsx] 
# command = "dnsx"               # Path to dnsx binary
# timeout_ms = 30000             # 30 seconds timeout for dnsx
# max_results = 1000             # Maximum subdomains to discover

# # httpx configuration for virtual host enumeration
# [tools.hosts_discovery.httpx]
# command = "httpx"              # Path to httpx binary  
# timeout_ms = 60000             # 60 seconds timeout for httpx
# max_results = 100              # Maximum vhosts to discover

# ========================================
# GLOBAL OVERRIDES
# ========================================

[overrides]
# Force specific tool versions or paths if needed
[overrides.paths]
nslookup = "/usr/bin/nslookup"   # Override nslookup path if needed
dig = "/usr/bin/dig"             # Override dig path if needed
dnsx = "/usr/local/bin/dnsx"     # Override dnsx path if needed
httpx = "/usr/local/bin/httpx"   # Override httpx path if needed

# Global timeout multipliers
[overrides.timeouts]
multiplier = 1.0                 # Multiply all timeouts by this factor
max_total_runtime_s = 300        # 5 minutes total scan limit

# ========================================
# OUTPUT CONFIGURATION
# ========================================
# Uncomment to override default output settings

# [output]
# # Template selection
# report_formats = ["txt", "md", "json"]
# default_template = "summary"

# # File naming patterns
# [output.naming]
# run_id_pattern = "run_{target}_{timestamp}"
# timestamp_format = "%Y%m%d_%H%M%S"

# # Artifact retention
# [output.retention]
# keep_raw_scans = true
# keep_plugin_results = true
# compress_old_runs = false
# max_run_history = 50

# ========================================
# LOGGING CONFIGURATION
# ========================================
# Uncomment to override default logging settings

# [logging]
# level = "info"                   # trace, debug, info, warn, error
# target = "file"                 # console, file, both
# max_file_size_mb = 10
# rotate_files = true

# ========================================
# VALIDATION RULES
# ========================================
# Uncomment to override default validation settings

# [validation]
# # Pre-flight checks for active tools only
# require_tools = ["nslookup", "dig", "dnsx", "httpx"]
# check_file_descriptors = true
# check_disk_space_mb = 100

# # Input validation  
# [validation.targets]
# allow_private_ips = true
# allow_localhost = true
# max_target_length = 253
# validate_dns = false

# ========================================
# PLUGIN SYSTEM
# ========================================
# Uncomment to override default plugin settings

# [plugins]
# # Plugin discovery and loading
# auto_discover = true
# plugin_dirs = ["./plugins", "./custom_plugins"]

# # Plugin execution order for active reconnaissance plugins
# [plugins.execution_order]
# reconnaissance = ["nslookup", "dig", "hosts_discovery"]
# port_scanners = []               # Empty - using reconnaissance plugins
# service_scanners = []            # Empty - no service scanning plugins active
# reporters = ["summary_reporter"]