[tools.whois_lookup]
name = "whois_lookup"
description = "WHOIS domain information"
command = "whois"
args = [
    "{target}"
]
output_file = "whois_{target}.txt"
category = "discovery"
dependencies = ["whois"]
parse_strategy = "llm"
output_format = "json"
requires_sudo = false
timeout_seconds = 60