# ========================================
# Global Wordlists and Settings
# ========================================
# Wordlists used by scanning tools
# Install wordlists: sudo apt install seclists wordlists

[global]
# ========================================
# Directory/Web Scanning Wordlists
# ========================================
# Used by: feroxbuster, gobuster, dirsearch, ffuf, dirb
directory-wordlist = '/usr/share/seclists/Discovery/Web-Content/directory-list-2.3-small.txt'

# ========================================
# DNS/Subdomain Scanning Wordlists  
# ========================================
# Used by: subdomain enumeration tools
subdomain-wordlist = '/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt'

# Used by: dnsrecon, fierce
dns-wordlist = '/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt'

# ========================================
# Virtual Host Discovery Wordlists
# ========================================
# Used by: virtual host enumeration tools
vhost-wordlist = '/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt'

# ========================================
# Credential/Bruteforce Wordlists
# ========================================
# Used by: hydra, medusa, crackmapexec for username bruteforcing
username-wordlist = '/usr/share/seclists/Usernames/top-usernames-shortlist.txt'

# Used by: hydra, medusa, crackmapexec for password bruteforcing  
password-wordlist = '/usr/share/seclists/Passwords/darkweb2017-top100.txt'

# ========================================
# Domain Settings
# ========================================
# Base domain for subdomain enumeration and DNS testing
# Example: domain = 'example.com'
domain = ''

# ========================================
# Wordlist Help/Comments
# ========================================
# Note: Smaller wordlists = faster scans
# - directory-list-2.3-small.txt: ~87K entries (recommended)
# - directory-list-2.3-medium.txt: ~220K entries (thorough)
# - subdomains-top1million-5000.txt: ~5K entries (fast)
# - subdomains-top1million-110000.txt: ~110K entries (comprehensive)
