# Global Configuration for ipcrawler
# ===================================
# This file contains global plugin defaults and pattern matching configurations.
# Wordlist management is handled automatically by SecLists detection.

# This file will only be used as fallback in case auto-detection of seclists fails.

[global.domain]
help = 'The domain to use (if known). Used for DNS and/or Active Directory. Default: %(default)s'

# Configure global pattern matching here.
[[pattern]]
description = 'Nmap script found a potential vulnerability. ({match})'
pattern = 'State: (?:(?:LIKELY\_?)?VULNERABLE)'

[[pattern]]
pattern = '(?i)unauthorized'

[[pattern]]
description = 'CVE Identified: {match}'
pattern = '(CVE-\d{4}-\d{4,7})'
