# ========================================
# Global Wordlists and Settings
# ========================================
# Wordlists used by scanning tools
# Install wordlists: sudo apt install seclists wordlists
#
# How it works:
# 1. ipcrawler tries to use the wordlist path you specify below
# 2. If that path doesn't exist, it automatically falls back to local wordlists
# 3. This means you can configure for HTB/Kali environments and it still works locally
#
# Path Resolution:
# - Relative paths (e.g., 'wordlists/file.txt') are resolved relative to global.toml location
# - Absolute paths (e.g., '/usr/share/seclists/...') are used as-is
# - ipcrawler/wordlists/ contains local fallback wordlists

[global]
# ========================================
# Directory/Web Scanning Wordlists
# ========================================
# Used by: feroxbuster, gobuster, dirsearch, ffuf, dirb

# Configured wordlist path (will fallback to local if not found)
directory-wordlist = '/usr/share/seclists/Discovery/Web-Content/directory-list-2.3-small.txt'

# Alternative: Use absolute path to SecLists (uncomment if installed)
# directory-wordlist = '/usr/share/seclists/Discovery/Web-Content/directory-list-2.3-small.txt'

# Alternative: Use custom wordlist anywhere on system
# directory-wordlist = '/home/user/custom-wordlists/my-directory-list.txt'

# ========================================
# DNS/Subdomain Scanning Wordlists  
# ========================================
# Used by: subdomain enumeration tools
subdomain-wordlist = '/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt'

# Used by: dnsrecon, fierce
dns-wordlist = '/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt'

# ========================================
# Virtual Host Discovery Wordlists
# ========================================
# Used by: virtual host enumeration tools
vhost-wordlist = '/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt'

# ========================================
# LFI (Local File Inclusion) Wordlists
# ========================================
# Used by: curl-lfi-test plugin for fallback ffuf scanning
# Small, focused wordlist for parameter discovery
lfi-parameter-wordlist = '/usr/share/seclists/Discovery/Web-Content/burp-parameter-names.txt'

# LFI payload wordlist for comprehensive testing
lfi-payload-wordlist = '/usr/share/seclists/Fuzzing/LFI/LFI-Jhaddix.txt'

# ========================================
# Credential/Bruteforce Wordlists
# ========================================
# Used by: hydra, medusa, crackmapexec for username bruteforcing
username-wordlist = '/usr/share/seclists/Usernames/top-usernames-shortlist.txt'

# Used by: hydra, medusa, crackmapexec for password bruteforcing  
password-wordlist = '/usr/share/seclists/Passwords/darkweb2017-top100.txt'

# ========================================
# Domain Settings
# ========================================
# Base domain for subdomain enumeration and DNS testing
# Example: domain = 'example.com'
domain = ''

# ========================================
# Wordlist Help/Comments
# ========================================
# Note: Smaller wordlists = faster scans
# - directory-list-2.3-small.txt: ~87K entries (recommended)
# - directory-list-2.3-medium.txt: ~220K entries (thorough)
# - subdomains-top1million-5000.txt: ~5K entries (fast)
# - subdomains-top1million-110000.txt: ~110K entries (comprehensive)
# - burp-parameter-names.txt: ~6K parameter names (LFI discovery)
# - LFI-Jhaddix.txt: ~900 LFI payloads (comprehensive LFI testing)
# - dirbuster.txt: ~116K entries (local fallback wordlist)
#
# Path Examples:
# Relative to global.toml:        'wordlists/my-list.txt'
# Absolute system path:           '/usr/share/seclists/Discovery/Web-Content/big.txt'
# User home directory:            '/home/username/wordlists/custom.txt'
# Current working directory:      './my-wordlists/list.txt'

# ========================================
# Configuration Examples for Different Environments
# ========================================
#
# 💡 How to customize wordlists:
#    Just change any path below to your preferred wordlist!
#    If your path doesn't exist, ipcrawler automatically falls back to local wordlists.
#
# Examples of different configurations:
#
# For local/portable usage (always works):
# directory-wordlist = 'wordlists/dirbuster.txt'
# vhost-wordlist = 'wordlists/subdomains-top100.txt'
#
# For custom wordlists:
# directory-wordlist = '/home/user/my-wordlists/huge-directory-list.txt'
# vhost-wordlist = '/opt/seclists/Discovery/DNS/subdomains-top1million-110000.txt'
#
# For different SecLists sizes:
# directory-wordlist = '/usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt'  # ~220K entries
# vhost-wordlist = '/usr/share/seclists/Discovery/DNS/subdomains-top1million-20000.txt'  # 20K entries
#
# Mixed configurations work too:
# directory-wordlist = '/usr/share/seclists/Discovery/Web-Content/big.txt'        # Use SecLists for directories
# vhost-wordlist = 'wordlists/subdomains-top100.txt'                             # Use local for vhosts
