# Output and Results Configuration
# Formatting, storage, and export settings

[formats]
# Available output formats
default_readable = "txt"           # Default human-readable format
machine_readable = "jsonl"         # Default machine-readable format
export_formats = ["txt", "md", "json", "jsonl", "xml", "csv", "html"]

# Format-specific settings
[formats.json]
prettify = true                    # Pretty-print JSON output
indent = 2                         # JSON indentation level
sort_keys = true                   # Sort JSON keys alphabetically

[formats.markdown]
style = "github"                   # Markdown style: github, gitlab, basic
include_toc = true                 # Include table of contents
syntax_highlighting = true        # Use syntax highlighting for code blocks
embed_images = false               # Embed images inline

[formats.csv]
delimiter = ","                    # CSV field delimiter
quote_char = "\""                  # CSV quote character
escape_char = "\\"                 # CSV escape character
include_headers = true             # Include column headers

[formats.xml]
root_element = "scan_results"      # Root XML element name
pretty_print = true                # Pretty-print XML output
encoding = "UTF-8"                 # XML encoding

[storage]
# Result storage settings
base_directory = "results"         # Base results directory
auto_compress_after_days = 30      # Compress results after N days
max_historical_runs = 50           # Maximum number of runs to keep
compress_format = "gzip"           # Compression format: gzip, bzip2, xz
retention_policy = "time_based"    # Retention policy: time_based, count_based, size_based

# Storage limits
max_result_size = 104857600        # Maximum size per result file (100MB)
max_total_storage = 10737418240    # Maximum total storage (10GB)
warning_threshold = 0.8            # Warn when storage is 80% full

# Backup settings
auto_backup = false                # Automatically backup results
backup_directory = "backups"       # Backup directory
backup_interval_hours = 24         # Backup interval
backup_retention_days = 30         # How long to keep backups

[organization]
# Result organization preferences
use_run_numbers = true             # Use run numbers for file separation
separate_by_date = false           # Organize by date instead of run numbers
group_by_target = true             # Group results by target
create_summaries = true            # Automatically create summary files
timestamp_format = "ISO8601"       # Timestamp format: ISO8601, UNIX, HUMAN

# Directory structure
create_subdirectories = true       # Create organized subdirectories
subdirectory_structure = [         # Subdirectory organization
    "readable",                    # Human-readable results
    "machine",                     # Machine-readable results  
    "success",                     # Successful scan records
    "errors"                       # Error records
]

[export]
# Export configuration
include_metadata = true            # Include scan metadata in exports
include_timestamps = true          # Include execution timestamps
include_execution_time = true      # Include execution duration
include_tool_versions = false      # Include tool version information
include_environment = false       # Include environment information

# Filtering options
exclude_empty_results = true       # Exclude results with no output
exclude_failed_scans = false      # Exclude failed scans from exports
min_execution_time = 0             # Minimum execution time to include (seconds)
max_execution_time = 0             # Maximum execution time to include (0 = no limit)

# CTF noise filtering (for cleaner results in competitive scenarios)
enable_ctf_filtering = true        # Enable CTF-specific noise filtering
filter_nmap_fingerprints = true    # Remove nmap service fingerprints (SF: lines)
filter_submission_prompts = true   # Remove tool submission/reporting prompts
filter_version_banners = false     # Remove verbose version banners
filter_debug_output = true         # Remove debug and verbose tool output

[templates]
# Output templates for different formats
use_custom_templates = false       # Use custom output templates
template_directory = "templates/output"
default_template = "standard"

# Template variables available: target, timestamp, results, metadata
[templates.variables]
include_scan_info = true           # Include scan information
include_system_info = false       # Include system information
include_statistics = true         # Include scan statistics

[notifications]
# Result notifications
notify_on_completion = false       # Notify when scans complete
notify_on_error = false           # Notify on scan errors
notify_on_discovery = false       # Notify on significant discoveries

# Notification methods
[notifications.webhook]
enabled = false
url = ""
method = "POST"
headers = {}
payload_template = "json"

[notifications.email]
enabled = false
smtp_server = ""
smtp_port = 587
username = ""
password = ""
from_address = ""
to_addresses = []
subject_template = "ipcrawler scan completed for {target}"

[notifications.slack]
enabled = false
webhook_url = ""
channel = "#security"
username = "ipcrawler"
icon_emoji = ":shield:"

[analytics]
# Result analytics and metrics
enable_analytics = true           # Enable result analytics
track_success_rates = true        # Track template success rates
track_execution_times = true      # Track execution performance
track_error_patterns = true       # Track common error patterns
generate_reports = true           # Generate periodic analytics reports

# Metrics collection
metrics_retention_days = 365      # How long to keep metrics
metrics_format = "json"           # Metrics storage format
aggregate_daily = true            # Create daily aggregated metrics
aggregate_weekly = true           # Create weekly aggregated metrics

[performance]
# Performance optimization settings
parallel_file_operations = true   # Parallelize file I/O operations
buffer_size = 65536               # File I/O buffer size (64KB)
compression_level = 6             # Compression level (1-9, higher = better compression)
async_writes = true               # Use asynchronous file writes
batch_operations = true           # Batch multiple operations together

# Caching
enable_caching = true             # Enable result caching
cache_directory = ".cache"        # Cache directory
cache_expiry_hours = 24          # Cache expiry time
max_cache_size = 1073741824      # Maximum cache size (1GB)

[security]
# Output security settings
sanitize_outputs = true          # Sanitize sensitive data in outputs
redact_credentials = true        # Redact credentials from results
mask_internal_ips = false        # Mask internal IP addresses
encrypt_sensitive_results = false # Encrypt sensitive results

# File permissions
result_file_permissions = "644"   # File permissions for result files
directory_permissions = "755"    # Directory permissions
restrict_access = false          # Restrict access to results directory

[debugging]
# Debugging and troubleshooting
verbose_logging = false          # Enable verbose output logging
debug_file_operations = false   # Debug file I/O operations
trace_execution = false         # Trace execution flow
save_debug_info = false         # Save debugging information to files
debug_output_directory = "debug" # Directory for debug files