# Security Configuration
# Validation rules and safety settings

[validation]
# Input validation settings
max_arg_length = 1000                 # Maximum length for individual arguments
max_args_count = 50                   # Maximum number of arguments per template
max_template_size = 1048576          # Maximum template file size (1MB)
max_target_length = 500              # Maximum target string length

# Security patterns to reject in arguments
dangerous_patterns = [
    "[;&|`$()]",      # Shell metacharacters
    "\\.\\./",        # Directory traversal
    "[<>]",           # Redirection operators
    "\\$\\(",         # Command substitution
    "`",              # Backticks
    "&&",             # Command chaining
    "\\|\\|",         # Command chaining
    ";",              # Command separator
    "\\\\x[0-9a-f]{2}" # Hex encoded characters
]

# Command injection prevention
whitelist_mode = false               # Only allow whitelisted commands
validate_all_inputs = true          # Validate all user inputs
sanitize_inputs = true              # Sanitize dangerous characters
escape_special_chars = true        # Escape shell special characters

[execution]
# Execution safety settings
allow_shell_execution = false       # Never allow shell=True
sandbox_mode = true                 # Run in sandboxed environment
resource_limits = true             # Enforce resource limits
network_restrictions = false       # Apply network restrictions (future)
chroot_jail = false                # Run in chroot jail (advanced)

# Sudo privilege settings
sudo_detection_enabled = true      # Enable sudo privilege detection
sudo_skip_gracefully = true        # Skip sudo plugins gracefully when not root
sudo_warn_user = true             # Warn user about skipped sudo plugins
sudo_file_paths_allowed = [        # File paths allowed for sudo operations
    "/etc/hosts",
    "/etc/hostname", 
    "/tmp/*",
    "/var/tmp/*"
]

# Process limits
max_execution_time = 300           # Maximum execution time per template (5 minutes)
max_memory_usage = 512             # Maximum memory per process (MB)
max_file_descriptors = 100        # Maximum open file descriptors
max_subprocess_count = 10          # Maximum number of concurrent subprocesses

# Tool restrictions
allowed_tools = [
    # Network scanning
    "nmap", "masscan", "zmap",
    # Web tools
    "curl", "wget", "httpx",
    # DNS tools
    "dig", "nslookup", "host",
    # Directory enumeration
    "feroxbuster", "gobuster", "dirb", "ffuf",
    # Vulnerability scanners
    "nuclei", "nikto", "wpscan", "sqlmap",
    # Password tools (controlled)
    "john", "hydra", "hashcat",
    # SSL/TLS tools
    "openssl", "sslscan", "testssl",
    # Basic utilities
    "ping", "echo", "cat", "head", "tail"
]

# Sudo-enabled tools (only allowed when requires_sudo: true)
sudo_enabled_tools = [
    # System file modification
    "tee",      # For writing to system files like /etc/hosts
    "touch",    # For creating files
    "mkdir",    # For creating directories
    # File permissions (limited scope)
    "chmod",    # For changing permissions
    "chown",    # For changing ownership
]

# Completely blocked tools
blocked_tools = [
    # System modification
    "rm", "del", "delete", "format", "mkfs",
    # System control
    "shutdown", "reboot", "halt", "poweroff",
    # User management
    "useradd", "userdel", "passwd", "su", "sudo",
    # Network modification
    "iptables", "ufw", "firewall-cmd",
    # File system
    "mount", "umount", "fsck", "fdisk",
    # Shells
    "sh", "bash", "zsh", "fish", "csh", "tcsh",
    # Interpreters (unless specifically needed)
    "python", "perl", "ruby", "php", "node"
]

[monitoring]
# Security monitoring and logging
log_all_executions = true          # Log every tool execution
log_failed_validations = true      # Log validation failures
log_security_events = true         # Log security-related events
detect_anomalies = true            # Monitor for unusual behavior
rate_limiting = true               # Apply rate limiting

# Rate limiting settings
max_executions_per_minute = 100    # Maximum tool executions per minute
max_failed_attempts = 10           # Maximum failed attempts before blocking
cooldown_period = 300              # Cooldown period after rate limit (seconds)
progressive_delays = true          # Increase delays for repeated violations

# Monitoring thresholds
high_cpu_threshold = 80            # CPU usage percentage to trigger alert
high_memory_threshold = 75         # Memory usage percentage to trigger alert
long_execution_threshold = 180     # Execution time to trigger alert (seconds)

[compliance]
# Compliance and auditing settings
audit_mode = false                 # Enable comprehensive audit logging
log_retention_days = 90           # How long to keep audit logs
encrypt_sensitive_data = true     # Encrypt sensitive data in logs
anonymize_targets = false         # Anonymize target information in logs
gdpr_compliance = false           # Enable GDPR compliance features

# Audit log settings
audit_log_file = "audit.log"
audit_log_format = "json"         # json, csv, or syslog
audit_log_rotation = true
max_audit_log_size = 104857600    # 100MB

[network]
# Network security settings (future implementation)
restrict_local_networks = false   # Block access to local networks
restrict_cloud_metadata = false   # Block cloud metadata endpoints
allowed_ports = []                # Empty = all ports allowed
blocked_ports = [22, 23, 3389]   # SSH, Telnet, RDP
dns_filtering = false             # Apply DNS-based filtering

# Network timeouts
connect_timeout = 10              # Connection timeout (seconds)
read_timeout = 30                # Read timeout (seconds)
max_redirects = 5                # Maximum HTTP redirects to follow

[data_protection]
# Data protection and privacy
mask_sensitive_data = true       # Mask sensitive data in outputs
redact_credentials = true        # Redact credentials from logs
secure_temp_files = true         # Use secure temporary files
auto_cleanup = true              # Automatically clean up temporary files
encrypted_storage = false        # Encrypt stored results (future)

# Sensitive data patterns to mask
sensitive_patterns = [
    # Credentials
    "(?i)(password|passwd|pwd)[:=]\\s*\\S+",
    "(?i)(api[_-]?key|apikey)[:=]\\s*\\S+",
    "(?i)(secret|token)[:=]\\s*\\S+",
    # Personal information  
    "\\b\\d{3}-\\d{2}-\\d{4}\\b",      # SSN
    "\\b\\d{4}[\\s-]?\\d{4}[\\s-]?\\d{4}[\\s-]?\\d{4}\\b", # Credit card
    # Network information
    "(?i)(private[_-]?key|rsa[_-]?key)[:=]\\s*\\S+",
]

[incident_response]
# Incident response settings
auto_quarantine = false           # Automatically quarantine suspicious templates
alert_on_violations = true        # Send alerts on security violations
emergency_stop = false            # Enable emergency stop functionality
contact_admin = false             # Auto-contact administrator on incidents

# Response actions
quarantine_directory = "quarantine"
incident_log_file = "incidents.log"
escalation_threshold = 5          # Number of violations before escalation

[updates]
# Security update settings
auto_update_signatures = false    # Auto-update security signatures
check_for_updates = true          # Check for security updates
update_check_interval = 86400     # Check interval in seconds (24 hours)
security_feed_url = ""            # URL for security feed updates