# Template Categories and Mappings
# User-customizable template organization

[categories]
# Flag shortcuts to template folders
# Format: flag_name = "folder_name"
# Usage: ipcrawler -flag_name target

# template name = folder name
htb = "htb"
testing = "testing"
wiz = "wizard"
wizard = "wizard"

# Add your custom template folders here
# Example:
# user = "custom_folder"
# corp = "corporate_tools"
# mobile = "mobile_security"

[metadata]
# Template discovery settings
scan_depth = 3              # How deep to search for templates
auto_discover = true        # Automatically discover new templates
cache_templates = true      # Cache template metadata for faster loading
refresh_cache_hours = 24    # How often to refresh template cache

[filters]
# Template filtering options
exclude_patterns = ["*test*", "*.backup", "*example*"]  # Skip these patterns
include_tags = ["production", "stable"]                 # Only load templates with these tags
exclude_tags = ["experimental", "broken"]               # Skip templates with these tags
min_quality_score = 7                                   # Minimum quality score (1-10)
max_timeout = 300                                        # Maximum allowed timeout per template

[validation]
# Template validation rules
require_description = true   # Require description field
require_tags = true         # Require tags field
require_author = false      # Require author field
validate_syntax = true     # Validate JSON syntax
validate_security = true   # Validate for security issues

# Allowed tools (security whitelist)
allowed_tools = [
    "nmap", "curl", "dig", "nuclei", "feroxbuster", "gobuster", 
    "ping", "echo", "openssl", "nslookup", "wpscan", "nikto",
    "dirb", "ffuf", "sqlmap", "john", "hydra", "masscan"
]

# Blocked tools (security blacklist)
blocked_tools = ["rm", "del", "format", "shutdown", "reboot"]

[organization]
# Template organization preferences
group_by_tool = false       # Group templates by tool type
group_by_category = true    # Group templates by category folder
auto_categorize = true      # Automatically categorize new templates
show_hidden = false         # Show templates in hidden folders
sort_by = "name"           # Sort templates by: name, date, author, quality

[display]
# Template display settings
show_descriptions = true    # Show template descriptions in lists
show_tags = true           # Show template tags
show_author = false        # Show template author
show_timeout = true        # Show template timeout values
truncate_description = 100 # Truncate descriptions to N characters

[defaults]
# Default values for new templates
default_timeout = 60       # Default timeout for new templates
default_tags = ["custom"]  # Default tags for new templates
default_parallel_safe = true  # Default parallel execution safety

# =============================================================================
# AUTO-WORDLIST SELECTION SYSTEM
# =============================================================================

[auto_wordlist]
# Auto-wordlist selection settings
enable = true                    # Master switch for auto-wordlist
cache_selections = true          # Cache selections for performance
debug_logging = false           # Log selection decisions

[auto_wordlist.scoring]
# Scoring weights (must sum to 1.0)
technology_weight = 0.4         # Weight for technology matching
context_weight = 0.3            # Weight for context/hint matching  
quality_weight = 0.3            # Weight for wordlist quality metrics
performance_weight = 0.0        # Reserved for future use

[auto_wordlist.preferences]
# User preferences for wordlist selection
prefer_ctf_optimized = true     # Prefer CTF-optimized wordlists
prefer_smaller_lists = true     # Prefer smaller, faster wordlists
max_wordlist_lines = 50000      # Maximum lines in selected wordlist
min_quality_score = 5           # Minimum quality score (1-10)
exclude_large_lists = true      # Exclude wordlists >10MB

[auto_wordlist.technology_mapping]
# Technology to wordlist category mapping (keep specific, avoid generic dilution)
php = ["php"]                    # PHP sites get PHP-specific wordlists
wordpress = ["wordpress", "php"] # WordPress gets WordPress + PHP wordlists
apache = ["apache"]
nginx = ["nginx"]
jsp = ["jsp"]                    # JSP gets JSP-specific wordlists
python = ["python"]
nodejs = ["nodejs"]
api = ["api"]
admin = ["admin"]

[auto_wordlist.context_hints]
# Context hints to wordlist preferences (avoid generic web dilution)
directory = ["directory"]        # Directory hint stays focused
admin = ["admin"]
api = ["api"]
vhost = ["dns", "subdomain", "vhost"]  # Added explicit vhost tag
backup = ["backup"]

[auto_wordlist.tool_preferences]
# Tool-specific wordlist preferences
gobuster = ["fast", "ctf_optimized"]
feroxbuster = ["medium", "recursive"]
dirb = ["small", "classic"]
ffuf = ["fast", "modern"]

[auto_wordlist.fallbacks]
# Fallback wordlists for different scenarios (auto detection will find appropriate paths)
default = "auto"
admin = "auto"
api = "auto" 
directory = "auto"
vhost = "auto"