# Wordlist Configuration
# Define wordlist aliases and their file paths for different scanning tools
# 
# Standard Kali Linux / HTB paths for SecLists:
#   /usr/share/seclists/Discovery/Web-Content/
#   /usr/share/seclists/Discovery/DNS/
# Install SecLists: 
#   - Kali/Ubuntu: sudo apt install seclists
#   - Manual: git clone https://github.com/danielmiessler/SecLists.git /usr/share/seclists

[wordlists]
# Default wordlist used when no -w/--wordlist flag is provided
default = "embedded-common"

# Embedded wordlists (included with ipcrawler - relative to templates directory)
[wordlists.embedded-common]
path = "wordlists/common.txt"
description = "Built-in common web paths (50+ entries) - FAST & ALWAYS AVAILABLE"
size = "tiny"

# SecLists - Web Content Discovery (requires SecLists installation)
[wordlists.common]
path = "/usr/share/seclists/Discovery/Web-Content/common.txt"
description = "SecLists common web content (4k entries)"
size = "small"

[wordlists.medium]
path = "/usr/share/seclists/Discovery/Web-Content/directory-list-2.3-medium.txt"
description = "SecLists directory list medium (220k entries)"
size = "medium"

[wordlists.big]
path = "/usr/share/seclists/Discovery/Web-Content/directory-list-2.3-big.txt"
description = "SecLists directory list big (1.2M entries)"
size = "large"

[wordlists.small]
path = "/usr/share/seclists/Discovery/Web-Content/common.txt"
description = "Alias for 'common' - fast scan (4k entries)"
size = "small"

# SecLists - Additional wordlists
[wordlists.raft-small]
path = "/usr/share/seclists/Discovery/Web-Content/raft-small-words.txt"
description = "SecLists Raft small words (43k entries)"
size = "small"

[wordlists.raft-medium]
path = "/usr/share/seclists/Discovery/Web-Content/raft-medium-words.txt"
description = "SecLists Raft medium words (63k entries)"
size = "medium"

[wordlists.raft-large]
path = "/usr/share/seclists/Discovery/Web-Content/raft-large-words.txt"
description = "SecLists Raft large words (107k entries)"
size = "large"

# API & Technology Specific
[wordlists.api-endpoints]
path = "/usr/share/seclists/Discovery/Web-Content/api/api-endpoints.txt"
description = "Common API endpoints (30+ entries)"
size = "small"

# DNS & Subdomain Discovery
[wordlists.subdomains-top1million-5000]
path = "/usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt"
description = "Top 5000 most common subdomains"
size = "small"

# Legacy - DIRB & DirBuster (Fallback for older systems)
[wordlists.dirb-common]
path = "/usr/share/wordlists/dirb/common.txt"
description = "DIRB common directory/file names (4614 entries)"
size = "small"

[wordlists.dirb-small]
path = "/usr/share/wordlists/dirb/small.txt"
description = "DIRB small directory list (959 entries)"
size = "small"

[wordlists.dirbuster-medium]
path = "/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt"
description = "DirBuster medium directory list (220k entries)"
size = "medium"

[wordlists.dirbuster-big]
path = "/usr/share/wordlists/dirbuster/directory-list-2.3-big.txt"
description = "DirBuster big directory list (1.2M entries)"
size = "large"

# Custom wordlists - add your own below
# [wordlists.custom]
# path = "/path/to/your/custom/wordlist.txt"
# description = "Your custom wordlist"
# size = "custom"
