name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target/
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install system dependencies and tools
      run: bash scripts/install_tools.sh

    - name: Verify tools installation
      run: bash scripts/check_tools.sh

    - name: Build release binary
      run: cargo build --release

    - name: Test binary execution
      run: |
        ./target/release/ipcrawler --version
        ./target/release/ipcrawler --help

    - name: Create artifact directory
      run: mkdir -p artifacts

    - name: Package binary (Linux)
      if: runner.os == 'Linux'
      run: |
        cp target/release/ipcrawler artifacts/
        cp global.toml artifacts/
        cd artifacts
        tar -czf ../ipcrawler-${{ runner.os }}-x86_64.tar.gz *

    - name: Package binary (macOS)
      if: runner.os == 'macOS'
      run: |
        cp target/release/ipcrawler artifacts/
        cp global.toml artifacts/
        cd artifacts
        tar -czf ../ipcrawler-${{ runner.os }}-x86_64.tar.gz *

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ipcrawler-${{ runner.os }}-x86_64
        path: ipcrawler-${{ runner.os }}-x86_64.tar.gz
        retention-days: 7